language: c
python:
  - "2.7"
compiler:
  - gcc
cache: ccache
os:
  - windows

matrix:
  include:
    - name: "haxm-windows"
      os: windows
      install:
        - choco install -y python2 --params '"/InstallDir:C:\tools\python27"'
        - choco install -y nasm
        - grep nasm "C:\ProgramData\chocolatey\logs\chocolatey.log"
        - choco install -y openssl.light
      script:
        - export PATH="$PATH:/c/Program Files (x86)/Microsoft Visual Studio/Installer/"
        - export MSVC=$(vswhere -latest -products "*" -requires Microsoft.Component.MSBuild -property installationPath)
        - export MSVC=$(echo /$MSVC | sed -e 's/\\/\//g' -e 's/://')
        - export PATH="$PATH:$MSVC/MSBuild/15.0/Bin/"
        - export PYTHON_HOME=C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\opt\bin
        - export NASM_PREFIX=C:\tools\nasm\
        #- cd philmd/edk2
        #$ pwd: /c/Users/travis/build/philmd/edk2
        - ./edksetup.bat Rebuild
        - build
        #set EDK_TOOLS_PATH=C:\Tools
        #set EDK_TOOLS_PATH=%WORKSPACE%\BaseTools
        #set WORKSPACE=C:\MyWork\Proj1\edk2
        #Installed to 'C:\Program Files\OpenSSL'
        #PATH environment variable does not have C:\Program Files\OpenSSL\bin in it. Adding...
        # (or in powershell/cmd.exe just type `refreshenv`).

