language: c
python:
  - "2.7"
compiler:
  - gcc
cache: ccache
os:
  - windows

matrix:
  include:
    - name: "haxm-windows"
      os: windows
      install:
        - choco install -y nasm
        - choco install -y openssl.light
      script:
        #- cd edk2
        #- nuget restore
        - export PATH="$PATH:/c/Program Files (x86)/Microsoft Visual Studio/Installer/"
        - export MSVC=$(vswhere -latest -products "*" -requires Microsoft.Component.MSBuild -property installationPath)
        - export MSVC=$(echo /$MSVC | sed -e 's/\\/\//g' -e 's/://')
        - export PATH="$PATH:$MSVC/MSBuild/15.0/Bin/"
        - edksetup
        - edksetup.bat
        - build
        #- set PYTHON_HOME=C:\Python27

